### ISSUE TITLE
Pissandshittium OS

### ISSUE THREAD

**Issue by andrigamerita** [Pissandshittium/pissandshittium#109] opened 2023-12-20 16:59 UTC
Our number 1 priority nowadays should really be Pissandshittium OS. You see, there are 2 main reasons:
* The current market is monopolized by Google with their Chrome OS, and following the ideals of Pissandshittium we need a competitor to that in the form of Pissandshittium OS.
* We could only need to mantain Pissandshittium OS, which works on all computers, and tell users to install that, instead of having to mantain 382723 different versions for the 23843843843 desktop OSes that people brag about using and are mad when a package for their OS isn't available.

There could be many other positive reasons to take the project this route, but I think I've said enough, I invite other people to give their opinion on this and maybe propose ways of reaching this goal effectively.

**Comment by ghost** [comment] 2023-12-20 21:52
Duplicate of https://github.com/Pissandshittium/pissandshittium/issues/62

**Closed as completed** 2023-12-22 07:08 UTC
